

services:

  api:
    build: .
    container_name: $IMAGE_API_CONTAINER_NAME
    ports:
      - "${IMAGE_API_PORT}:${IMAGE_API_PORT}"
    command: uvicorn main:app --host $IMAGE_API_HOST --port $IMAGE_API_PORT
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      storage:
        condition: service_healthy

  db:
    image: postgres:18
    container_name: $DB_CONTAINER_NAME
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    expose:
      - "${DB_PORT}"
    volumes: 
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  cache:
    image: redis:7
    container_name: $CACHE_CONTAINER_NAME
    expose:
      - "${CACHE_PORT}"
    volumes:
      - "redis_data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  storage:
    image: minio/minio:17
    container_name: $STORAGE_CONTAINER_NAME
    ports:
      - "${STORAGE_PORT}:${STORAGE_PORT}"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${STORAGE_PORT}/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      storage:
        condition: service_healthy
    

volumes:
  postgres_data:
  redis_data:
  minio_data: